### ISSUE TITLE
Small objects get clipped even if I set camera.Near to very low values

### ISSUE THREAD

**Issue by eliasdaler** [SolarLune/tetra3d#21] opened 2022-07-29 11:55 UTC
Hello. 
I have noticed that some objects in my scene are disappearing once I get close to them.
I thought that I could fix that by setting Near value lower, but unfortunately this didn't help.
See [the modified scene from shapes example](https://files.catbox.moe/6vgd0g.gltf). 

Left to Suzanne, there is an object which disappears if you get close to it.
You can also see it being clipped even if you don't get close but rotate camera around sometimes.
![image](https://user-images.githubusercontent.com/1285136/181753382-141e6854-72ee-406f-92e5-37fad803694e.png)

**Comment by SolarLune** [comment] 2022-08-07 00:23
Yo, hello - I looked into this, and I don't think the issue is the size of the disappearing object. Instead, I think the issue is that the mesh is offset from the center, which is making the frustum sphere of the object misaligned. 

However, I can't reproduce it on my side by just offsetting a mesh; the frustum seems properly aligned in my case.

Do you have the blend file source of this?

**Comment by SolarLune** [comment] 2022-08-07 00:40
OK, nevermind, it has to do with having non-zero scale; must have missed that possibility when I was working on transform changes. This'll be fixed in a second; thanks for the report!

**Comment by SolarLune** [comment] 2022-08-07 07:20
OK, this should be resolved in master now. Thanks for the report!

**Closed by SolarLune** 2022-08-07 07:20 UTC
